# https://taskfile.dev

version: "3"

vars:
  INSTALL_DIR: ~/.claude/skills

tasks:
  validate:
    desc: Validate the skill structure
    cmds:
      - |
        if [ ! -f "{{.SKILL_DIR}}/SKILL.md" ]; then
          echo "Error: SKILL.md not found"
          exit 1
        fi
        if ! head -1 "{{.SKILL_DIR}}/SKILL.md" | grep -q "^---$"; then
          echo "Error: SKILL.md must start with YAML frontmatter (---)"
          exit 1
        fi
        echo "Skill structure is valid"

  sc:update:
    desc: Update the skill-creator package in ~/.claude from https://github.com/anthropics/skills/tree/main/skills/skill-creator
    cmds:
      - |
        TMPDIR=$(mktemp -d)
        trap 'rm -rf "$TMPDIR"' EXIT
        git clone --depth 1 --filter=blob:none --sparse \
          https://github.com/anthropics/skills.git "$TMPDIR"
        cd "$TMPDIR"
        git sparse-checkout set skills/skill-creator
        rm -rf ~/.claude/skills/skill-creator
        cp -r skills/skill-creator ~/.claude/skills/skill-creator
        echo "Updated skill-creator from upstream"

  install:
    desc: Symlink the skill for development (changes reflect immediately)
    cmds:
      - |
        SKILL_DIR=$(find . -type d -iname '*skill*' | fzf)
        test -z "$SKILL_DIR" && echo "Error: No skill selected" && exit 1
        SKILL_NAME=$(basename $(dirname "$SKILL_DIR"))
        SKILL_PATH="$(pwd)/{{.SKILL_DIR}}"
        test -f "$SKILL_PATH" || echo "Error: $SKILL_PATH is not a file" && exit 1
        echo "SKILL_DIR=$SKILL_DIR  SKILL_NAME=$SKILL_NAME"
        mkdir -p {{.INSTALL_DIR}}
        rm -irf {{.INSTALL_DIR}}/$SKILL_NAME
        ln -s "$SKILL_PATH" {{.INSTALL_DIR}}/$SKILL_NAME
